// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvclufbcorgxpvmlusqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2Y2x1ZmJjb3JneHB2bWx1c3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5MjE1OTgsImV4cCI6MjA4NjQ5NzU5OH0.MqoWdPlMq5s29h40t_IN-8sa1YgFakKXc1iypskYi3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});