// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irqddyqpfxxcxfnmlodz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlycWRkeXFwZnh4Y3hmbm1sb2R6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzExODAsImV4cCI6MjA2MzQwNzE4MH0.fJXOTjG-cwoAHsav3-ZhOfRAWr4CtBrhpxE22W7QJlo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);