// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// For browser/app usage (Vite)
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);

// For Node/tsx scripts (async, uses dotenv)
export const supabasePromise = (async () => {
  if (typeof window === 'undefined') {
    const dotenv = await import('dotenv');
    dotenv.config();
    const url = process.env.VITE_SUPABASE_URL;
    const key = process.env.VITE_SUPABASE_ANON_KEY;
    if (!url || !key) throw new Error('Supabase environment variables are not set.');
    return createClient<Database>(url, key);
  }
  return supabase;
})();